# Generated by Django 3.1.4 on 2021-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('publishingDatetime', models.DateTimeField()),
                ('publishedAfter', models.DateTimeField(blank=True, null=True)),
                ('thumbnailURL', models.URLField(max_length=500)),
            ],
        ),
    ]
